<a href="https://colab.research.google.com/github/AgrimaOjha/E_G17_SpotifyPulse/blob/main/01_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
# Load raw dataset
df = pd.read_csv("spotify_user_behavior_realistic_50000_rows.csv")

In [5]:
df.head()

,user_id,country,age,signup_date,subscription_type,subscription_status,months_inactive,inactive_3_months_flag,ad_interaction,ad_conversion_to_subscription,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,favorite_genre,most_liked_feature,desired_future_feature,primary_device,playlists_created,avg_skips_per_day
0,1,France,25,2021-08-19,Premium Duo,Active,0,0,No,No,4,10.13,Bollywood,Radio,Concert Alerts,Tablet,7,8
1,2,Indonesia,20,2022-06-06,Premium Family,Active,0,0,Yes,No,5,11.63,Latin,Podcasts,Lyrics Translation,Mobile,7,6
2,3,Italy,53,2024-01-04,Premium Individual,Active,0,0,Yes,Yes,3,9.50,Bollywood,Lyrics,Better AI Recommendations,Desktop,6,5
3,4,Italy,48,2018-08-26,Premium Individual,Active,1,0,No,No,4,13.16,Electronic,Playlists,Social Listening,Smart Speaker,11,8
4,5,Australia,18,2020-05-29,Free,Active,0,0,No,No,4,12.70,Indie,Daily Mix,Lyrics Translation,Tablet,10,11

In [6]:
# Shape of dataset
df.shape

(50000, 18)

In [7]:
# Column names
df.columns

Index(['user_id', 'country', 'age', 'signup_date', 'subscription_type',
       'subscription_status', 'months_inactive', 'inactive_3_months_flag',
       'ad_interaction', 'ad_conversion_to_subscription',
       'music_suggestion_rating_1_to_5', 'avg_listening_hours_per_week',
       'favorite_genre', 'most_liked_feature', 'desired_future_feature',
       'primary_device', 'playlists_created', 'avg_skips_per_day'],
      dtype='object')

In [8]:
# Data types
df.dtypes

user_id                             int64
country                            object
age                                 int64
signup_date                        object
subscription_type                  object
subscription_status                object
months_inactive                     int64
inactive_3_months_flag              int64
ad_interaction                     object
ad_conversion_to_subscription      object
music_suggestion_rating_1_to_5      int64
avg_listening_hours_per_week      float64
favorite_genre                     object
most_liked_feature                 object
desired_future_feature             object
primary_device                     object
playlists_created                   int64
avg_skips_per_day                   int64
dtype: object

In [9]:
# Info summary
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 18 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   user_id                         50000 non-null  int64
 1   country                         50000 non-null  object
 2   age                             50000 non-null  int64
 3   signup_date                     50000 non-null  object
 4   subscription_type               50000 non-null  object
 5   subscription_status             50000 non-null  object
 6   months_inactive                 50000 non-null  int64
 7   inactive_3_months_flag          50000 non-null  int64
 8   ad_interaction                  50000 non-null  object
 9   ad_conversion_to_subscription   50000 non-null  object
 10  music_suggestion_rating_1_to_5  50000 non-null  int64
 11  avg_listening_hours_per_week    50000 non-null  float64
 12  favorite_genre                  50000 non-null  object
 13  most_liked_feature              50000 non-null  object
 14  desired_future_feature          50000 non-null  object
 15  primary_device                  50000 non-null  object
 16  playlists_created               50000 non-null  int64
 17  avg_skips_per_day               50000 non-null  int64
dtypes: float64(1), int64(7), object(10)
memory usage: 6.9+ MB

In [12]:
df.describe()

,user_id,age,months_inactive,inactive_3_months_flag,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,playlists_created,avg_skips_per_day
count,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,38.010280,1.533020,0.222460,3.644100,9.988986,8.002680,10.025920
std,14433.901067,12.984989,1.952082,0.415903,1.114424,3.968927,2.831571,3.165579
min,1.000000,16.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,12500.750000,27.000000,0.000000,0.000000,3.000000,7.280000,6.000000,8.000000
50%,25000.500000,38.000000,1.000000,0.000000,4.000000,9.980000,8.000000,10.000000
75%,37500.250000,49.000000,2.000000,0.000000,5.000000,12.680000,10.000000,12.000000
max,50000.000000,60.000000,18.000000,1.000000,5.000000,26.250000,23.000000,25.000000