In [ ]:
import pandas as pd
df=pd.read_csv("/content/spotify_user_behavior_realistic_50000_rows.csv")

In [ ]:
df.head()

,user_id,country,age,signup_date,subscription_type,subscription_status,months_inactive,inactive_3_months_flag,ad_interaction,ad_conversion_to_subscription,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,favorite_genre,most_liked_feature,desired_future_feature,primary_device,playlists_created,avg_skips_per_day
0,1,France,25,2021-08-19,Premium Duo,Active,0,0,No,No,4,10.13,Bollywood,Radio,Concert Alerts,Tablet,7,8
1,2,Indonesia,20,2022-06-06,Premium Family,Active,0,0,Yes,No,5,11.63,Latin,Podcasts,Lyrics Translation,Mobile,7,6
2,3,Italy,53,2024-01-04,Premium Individual,Active,0,0,Yes,Yes,3,9.50,Bollywood,Lyrics,Better AI Recommendations,Desktop,6,5
3,4,Italy,48,2018-08-26,Premium Individual,Active,1,0,No,No,4,13.16,Electronic,Playlists,Social Listening,Smart Speaker,11,8
4,5,Australia,18,2020-05-29,Free,Active,0,0,No,No,4,12.70,Indie,Daily Mix,Lyrics Translation,Tablet,10,11

In [ ]:
df.duplicated().sum()
df = df.drop_duplicates()

In [ ]:
df['signup_date'] = pd.to_datetime(df['signup_date'])

In [ ]:
df['country'] = df['country'].str.lower().str.strip()

In [ ]:
df['subscription_type'] = df['subscription_type'].str.lower().str.strip()

In [ ]:
df.isnull().sum()

user_id                           0
country                           0
age                               0
signup_date                       0
subscription_type                 0
subscription_status               0
months_inactive                   0
inactive_3_months_flag            0
ad_interaction                    0
ad_conversion_to_subscription     0
music_suggestion_rating_1_to_5    0
avg_listening_hours_per_week      0
favorite_genre                    0
most_liked_feature                0
desired_future_feature            0
primary_device                    0
playlists_created                 0
avg_skips_per_day                 0
dtype: int64

In [ ]:
df['age'].mean()
df['age'].median()

38.0

In [ ]:
Q1=df['age'].quantile(0.25)
Q3=df['age'].quantile(0.75)
IQR=Q3-Q1
lower_bound=Q1-1.5*IQR
upper_bound=Q3+1.5*IQR

In [ ]:
df = df[(df['age']>=lower_bound) & (df['age']<=upper_bound)]

In [ ]:
df['age']=df['age'].fillna(df['age'].mean())
df['country']=df['country'].fillna('unknown')

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

user_id                           0
country                           0
age                               0
signup_date                       0
subscription_type                 0
subscription_status               0
months_inactive                   0
inactive_3_months_flag            0
ad_interaction                    0
ad_conversion_to_subscription     0
music_suggestion_rating_1_to_5    0
avg_listening_hours_per_week      0
favorite_genre                    0
most_liked_feature                0
desired_future_feature            0
primary_device                    0
playlists_created                 0
avg_skips_per_day                 0
dtype: int64

In [ ]:
df.describe()

,user_id,age,signup_date,months_inactive,inactive_3_months_flag,music_suggestion_rating_1_to_5,avg_listening_hours_per_week,playlists_created,avg_skips_per_day
count,50000.000000,50000.000000,50000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000,50000.000000
mean,25000.500000,38.010280,2022-02-01 03:01:50.591999744,1.533020,0.222460,3.644100,9.988986,8.002680,10.025920
min,1.000000,16.000000,2018-01-01 00:00:00,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,12500.750000,27.000000,2020-01-19 00:00:00,0.000000,0.000000,3.000000,7.280000,6.000000,8.000000
50%,25000.500000,38.000000,2022-01-31 00:00:00,1.000000,0.000000,4.000000,9.980000,8.000000,10.000000
75%,37500.250000,49.000000,2024-02-16 00:00:00,2.000000,0.000000,5.000000,12.680000,10.000000,12.000000
max,50000.000000,60.000000,2026-03-01 00:00:00,18.000000,1.000000,5.000000,26.250000,23.000000,25.000000
std,14433.901067,12.984989,NaN,1.952082,0.415903,1.114424,3.968927,2.831571,3.165579

In [ ]:
df.isnull().sum()

user_id                           0
country                           0
age                               0
signup_date                       0
subscription_type                 0
subscription_status               0
months_inactive                   0
inactive_3_months_flag            0
ad_interaction                    0
ad_conversion_to_subscription     0
music_suggestion_rating_1_to_5    0
avg_listening_hours_per_week      0
favorite_genre                    0
most_liked_feature                0
desired_future_feature            0
primary_device                    0
playlists_created                 0
avg_skips_per_day                 0
dtype: int64

In [ ]:
df['age_group'] = 'unknown'
df.loc[df['age'] < 12, 'age_group'] = 'child'
df.loc[(df['age'] >= 12) & (df['age'] < 20), 'age_group'] = 'teenager'
df.loc[(df['age'] >= 20) & (df['age'] < 25), 'age_group'] = 'young_adult'
df.loc[(df['age'] >= 25) & (df['age'] < 35), 'age_group'] = 'adult'
df.loc[(df['age'] >= 35) & (df['age'] < 50), 'age_group'] = 'mid_age'
df.loc[df['age'] >= 50, 'age_group'] = 'senior'

In [ ]:
df['inactive_3_months_flag'] = (df['months_inactive'] >= 3).astype(int)

In [ ]:
# df['ad_interaction'] = df['ad_interaction'].map({'Yes': 1, 'No': 0})
# df['ad_conversion_to_subscription'] = df['ad_conversion_to_subscription'].map({'Yes': 1, 'No': 0})

In [ ]:
df['engagement_score'] = (
    df['avg_listening_hours_per_week'] * 0.4 +
    df['playlists_created'] * 0.3 -
    df['avg_skips_per_day'] * 0.3
).round(3)
df['engagement_level'] = pd.qcut(df['engagement_score'], 3, labels=['Low', 'Medium', 'High'])

In [ ]:
df['subscription_type'] = df['subscription_type'].str.lower().str.strip()
df['most_liked_feature'] = df['most_liked_feature'].str.lower().str.strip()

In [ ]:
df

,user_id,country,age,signup_date,subscription_type,subscription_status,months_inactive,inactive_3_months_flag,ad_interaction,ad_conversion_to_subscription,...,avg_listening_hours_per_week,favorite_genre,most_liked_feature,desired_future_feature,primary_device,playlists_created,avg_skips_per_day,age_group,engagement_score,engagement_level
0,1,france,25,2021-08-19,premium duo,Active,0,0,No,No,...,10.13,Bollywood,radio,Concert Alerts,Tablet,7,8,adult,3.752,Medium
1,2,indonesia,20,2022-06-06,premium family,Active,0,0,Yes,No,...,11.63,Latin,podcasts,Lyrics Translation,Mobile,7,6,young_adult,4.952,High
2,3,italy,53,2024-01-04,premium individual,Active,0,0,Yes,Yes,...,9.50,Bollywood,lyrics,Better AI Recommendations,Desktop,6,5,senior,4.100,Medium
3,4,italy,48,2018-08-26,premium individual,Active,1,0,No,No,...,13.16,Electronic,playlists,Social Listening,Smart Speaker,11,8,mid_age,6.164,High
4,5,australia,18,2020-05-29,free,Active,0,0,No,No,...,12.70,Indie,daily mix,Lyrics Translation,Tablet,10,11,teenager,4.780,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,india,33,2022-09-23,free,Active,2,0,Yes,No,...,11.83,Latin,offline mode,Concert Alerts,Tablet,8,5,adult,5.632,High
49996,49997,italy,35,2023-11-17,premium family,Active,0,0,No,No,...,8.01,Latin,podcasts,Mood-based Auto Playlists,Car System,11,10,mid_age,3.504,Medium
49997,49998,brazil,33,2024-11-14,premium individual,Active,0,0,No,No,...,14.47,Rock,lyrics,Lyrics Translation,Smart Speaker,9,13,adult,4.588,High
49998,49999,usa,43,2021-05-31,free,Active,0,0,No,No,...,21.86,Indie,ai dj,Social Listening,Mobile,9,12,mid_age,7.844,High
49999,50000,indonesia,38,2024-07-05,free,Inactive,3,1,No,No,...,13.30,Rock,podcasts,Better AI Recommendations,Tablet,9,12,mid_age,4.420,High

In [ ]:
df.to_csv("spotify_cleaned.csv", index=False)

In [ ]:
df.isnull().sum()

user_id                           0
country                           0
age                               0
signup_date                       0
subscription_type                 0
subscription_status               0
months_inactive                   0
inactive_3_months_flag            0
ad_interaction                    0
ad_conversion_to_subscription     0
music_suggestion_rating_1_to_5    0
avg_listening_hours_per_week      0
favorite_genre                    0
most_liked_feature                0
desired_future_feature            0
primary_device                    0
playlists_created                 0
avg_skips_per_day                 0
age_group                         0
engagement_score                  0
engagement_level                  0
dtype: int64

In [ ]:
cleaned=df=pd.read_csv("/content/spotify_cleaned.csv")

In [ ]:
cleaned.isnull().sum()

user_id                           0
country                           0
age                               0
signup_date                       0
subscription_type                 0
subscription_status               0
months_inactive                   0
inactive_3_months_flag            0
ad_interaction                    0
ad_conversion_to_subscription     0
music_suggestion_rating_1_to_5    0
avg_listening_hours_per_week      0
favorite_genre                    0
most_liked_feature                0
desired_future_feature            0
primary_device                    0
playlists_created                 0
avg_skips_per_day                 0
age_group                         0
engagement_score                  0
engagement_level                  0
dtype: int64